### ISSUE TITLE
Allow the usage of payment method objects as a saved card

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#1102]
Allow the usage of PaymentMethod objects when they are imported.

Even though it's not necessary to replace the sources API with the PaymentMethods API completely within the plugin, we should allow imported payment methods to be used.

In terms of the properties we use, PaymentMethods are relatively similar to sources. This means that the necessary changes should be minimal:

- Modifying `WC_Stripe_Payment_Gateway::get_source_object` to use the PaymentMethods API instead of sources, whenever the ID of the object starts with `pm_`.
- Copying and modifying some conditions to check for `payment_method` `object`s along with `source`s.

p7bbVw-3vL-p2

**Comment by mouligreenlaw** [comment]
This ticket might be the same issue:
2550039-zen
User is trying to add a new Stripe token to a customers account via Subscriptions Payment Details but is is not being saved.
Token has a `seti_` prefix 
Token from Stripe has

**Comment by jessLundie** [comment]
Also seen in 2623501-zen

**Comment by gppuddinpie** [comment]
Is there any goal date for this to be complete? I'm unable to use Subscriptions until this has been fixed, as Stripe now only uses PMI and I'm unable to convert my existing customer subscriptions over without it.

**Comment by radiolize** [comment]
We are also still waiting for a very long time, we are not able to migrate our current subscribers to Woocommerce Subscriptions and waiting for this to be done to buy Woocommerce Subscriptions.

**Comment by jrick1229** [comment]
Also seen in: 3160959-zen

**Comment by trulslie** [comment]
Hi. I also have been talking with WC in support about WC Subscribers not accepting the stripe src_ codes, as generated from when I earlier had Memberpress, (which also added a renewal stripe subscription). 
 Strangely new WCS orders works with src_ generated from Card ID. 
And adding manuelly old subscriptions, when customer card ID had a card_ code, works find with renewals. 
WC special support says they now will be back on the issue, since these manually added subscriptilns, make stripe react with error, saying the "pm_ should be used...

**Comment by jacoswan** [comment]
Also seen in: 3172124-zen

**Comment by GeoJunkie** [comment]
This came up also in 3174320-zen .

**Comment by trulslie** [comment]
> Also seen in: 3172124-zen

How do I see this link?

**Comment by jessLundie** [comment]
> How do I see this link?

@trulslie You won't actually be able to see that link. The -zen and -hc numbers are internal ticket reference numbers used by the WooCommerce team to track customer cases.

**Comment by gppuddinpie** [comment]
There's a solution another user discovered, though it requires modifying original files: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1181#issuecomment-642433546

This has worked for me to import subscriptions.

**Comment by NickGreen** [comment]
We ran into this problem on a partner site. We chose to use the workaround of modifying the Stripe plugin and running that version, which:

- Changes the validation to also accept payment tokens with `pm_` prefix
- Changes the payment request payload to include `payment_method`

It’s not ideal to be running a modified version of the Stripe plugin, but it does provide a test case for that code, in case we want to add it to the main plugin at some point.

**Comment by radiolize** [comment]
Because of this issue, woocommerce subscription plugin probably lost a lot of active businesses such as us for last 9 months as people are still not able to migrate their current subscribers for **9 long months**. The plugin's users -who paid 200 usd for it- [are trying to find a solution themselves for months instead of well-known woocommerce's developers or product leads](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1181) and still no news.

Can you guys tell your customers such as us when it will be done as **we are tired of seeing delayed milestones?** Should we wait forever or we are about to find another solution instead of woocommerce subscription plugin.

Thanks.

**Comment by dechov** [comment]
@RadoslavGeorgiev Would https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1331 close this despite not touching `get_source_object` or any use of Sources besides the one?

**Comment by RadoslavGeorgiev** [comment]
@dechov #1331 fixes the biggest part of this issue: migrated subscriptions. However, I believe that migrations from other platforms might also import existing Payment Methods, which should be usable as saved cards.

I did this locally and it failed:
1. Go through checkout with a new card and make sure to save it.
2. In the database, replace some values with those from the CURL commands [in your PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1331):
    - The customer ID in `wp_usermeta` with the new customer.
    - The source ID with the payment method ID in `wp_woocommerce_payment_tokens`.
3. Try to check out with the saved card. You'll see another error, stating that the given `pm_***` source does not exist.

**Comment by dechov** [comment]
Ah, I hadn't considered the saved cards 👍 – thanks.

**Comment by paultannenbaum** [comment]
Is there any update on this, or when you guys plan on putting out a new release that includes #1331? There are several of us waiting in limbo until there is a release that includes this work. If it is going to be a while before a release that includes #1331, is there any kind of documentation on how we can run the master branch of this on our projects, meaning is there any kind of compile step or can I just download the repo and put it in the `plugins` directory?

**Comment by dechov** [comment]
@paultannenbaum Thanks for checking in – it's been released as of yesterday evening.

**Comment by paultannenbaum** [comment]
I saw that, currently implementing it into our app as we speak. Thank you all for your hard work on this 🙌

**Comment by thisissandip** [comment]
@dechov are we good to close this issue (considering this https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1331 resolves it)?

**Comment by thenbrent** [comment]
@dechov can we consider this issue resolved now that https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1331 is merged? Or is [this piece](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1102#issuecomment-706163289) still to be addressed with this issue?

**Comment by dechov** [comment]
Thanks for the pings – @RadoslavGeorgiev or @diegocurbelo might have a better idea of the scope of the issue, but my understanding is that being able to use the saved cards _on checkout_ was included and still not working.

**Comment by diegocurbelo** [comment]
Fixed with the new checkout release back in `8.0.0`
