### ISSUE TITLE
Title not respected using new checkout

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-gateway-stripe#2120]
**Describe the bug**
When the new checkout experience box is checked, the title added for Stripe is not displayed at checkout.

**To Reproduce**
Check this box:

<img width="1224" alt="Screen Shot 2021-11-05 at 1 27 08 PM" src="https://user-images.githubusercontent.com/8306136/140553099-69909aab-0641-4b77-9be0-d14671efcd94.png">

Add a title to Stripe, save, and visit checkout. The custom does NOT show up.

<img width="838" alt="Screen Shot 2021-11-05 at 1 24 17 PM" src="https://user-images.githubusercontent.com/8306136/140553152-7c6f4e39-04c3-4d55-8c84-f52af0e67519.png">

Uncheck the new checkout experience box, and return to checkout and the correct/custom title does show up

**Expected behavior**
I would expect the title to be respected, or another option for using that title in the new experience be provided.

**Environment (please complete the following information):**
 - WordPress Version 5.8.1
 - WooCommerce Version 5.8
 - Stripe Plugin Version 5.7

**Comment by ricardo** [comment]
@melindahelt when you mention that the title does not show up. No title shows up at all or there's a different title on the checkout page?

It's expected behavior that when "new checkout experience" is enabled, a different title shows up.
When multiple local payment methods are available, it should display "Popular payment methods" by default, because of the different payment methods all aggregated in the same gateway.

If only one payment method is available from the new checkout experience, it should display a title describing only that payment method.

On the other hand, if no title shows up at all, this might be related to another issue where the payment method title stays blank after submitting the settings form: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2039.

**Comment by melindahelt** [comment]
In my test, I only have credit card enabled and there is a title, however the user in this case wanted their custom title to appear
<img width="541" alt="Screen Shot 2021-11-16 at 9 30 34 AM" src="https://user-images.githubusercontent.com/8306136/142004238-ba1b6fff-9340-42d1-b11d-f5569f503562.png">

I'll let them know this is intended behavior

**Comment by demaya** [comment]
I see the same thing. I have a german page and cannot change the credit card payment option to a german value. Tried on different devices with different language settings, stays english.
![image](https://user-images.githubusercontent.com/1875832/142603377-476424db-6fdd-4b81-b2b8-69f9157e17d3.png)

Earlier this morning upgraded to 5.8.0 but the new setting doesn't change anything. (well I have only one payment method (cc) activated):
![image](https://user-images.githubusercontent.com/1875832/142603726-03c7b688-308c-4edb-b46e-5f7334a8a77f.png)

Thanks for investigating @ricardo in advance

**Comment by ricardo** [comment]
cc @LevinMedia / @jarekmorawski 

Currently there's no way to customize individual UPE payment method names.

When UPE is enabled, the default name which appears in the checkout page is "Popular payment methods", it can be customized in the screenshot @demaya shared, but when there's just one payment method available, e.g credit card. it will display a non-customizable translated string for the payment method name: `Pay with {PAYMENT_METHOD_NAME}`.

Do we want to allow customization of UPE payment method names?

**Comment by demaya** [comment]
Maybe a question can help you answering your question: do you have non-english speaking customers at Stripe? If yes: those texts should be translated for end consumers.

**Comment by jarekmorawski** [comment]
> Currently there's no way to customize individual UPE payment method names.

AFAIK, UPE will translate payment method names by default. Even if it's not available now, it should be in the future. I'll reach out to Stripe to double check. As for the issue, it looks like it can be solved by the adding translatable fields for payment method name and description.

**Comment by ricardo** [comment]
> AFAIK, UPE will translate payment method names by default. Even if it's not available now

Yes, Stripe should translate UPE fields, but the string highlighted in [this screenshot](https://user-images.githubusercontent.com/1875832/142603377-476424db-6fdd-4b81-b2b8-69f9157e17d3.png) comes from the plugin. It's a localized string, but still needs to be translated by the community.

**Comment by demaya** [comment]
What do you need to make progress here? Translation to german?

**Comment by ricardo** [comment]
@demaya yes, since there's no way to add a custom title for the gateway, we need the title translated to German. You are welcome to contribute to the German translation project:

German `de_DE`:
https://translate.wordpress.org/locale/de/default/wp-plugins/woocommerce-gateway-stripe/

German (Austria) `de_AT`:
https://translate.wordpress.org/locale/de-at/default/wp-plugins/woocommerce-gateway-stripe/

German (Switzerland) `de_CH`:
https://translate.wordpress.org/locale/de-ch/default/wp-plugins/woocommerce-gateway-stripe/

**Comment by jarekmorawski** [comment]
> Yes, Stripe should translate UPE fields, but the string highlighted in this screenshot comes from the plugin. It's a localized string, but still needs to be translated by the community.

Yup! Stripe confirmed that the UPE supports 42 locales. Regarding the string, it's basically the payment method name. We've discussed on Slack adding fields for the name and description (issue #2145). If we wanted to go the extra mile, we could add [Google-powered machine translation](https://cloud.google.com/translate) for the default string. I think that should solve the problem!

**Comment by niccolobusato** [comment]
Still having some problems with the italian translation.. ![image](https://user-images.githubusercontent.com/44100360/143205271-ccdeefdf-3ef9-469a-b116-903f76990e83.jpeg)

as u can see only the title isn't translated to italian out of the box

**Comment by amElnagdy** [comment]
With 5.8.1, when I change the name in the display settings, it does not affect the name on the checkout page.

It turned out that disabling the new checkout experience as shown
![https://d.pr/i/Uf0v50](https://d.pr/i/Uf0v50+) 
Full Size: https://d.pr/i/Uf0v50

will bring back the old (working) experience.

Ref: 4541964-zen

**Comment by amElnagdy** [comment]
Another report where the customer can't edit the payment method title: 1263201-hc

**Comment by demaya** [comment]
Any updates on this?

**Comment by demaya** [comment]
[Added the translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe/stable/de/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12571385&filters%5Btranslation_id%5D=95327630). Can you please approve @ricardo / @jarekmorawski. Thanks in advance.

**Comment by ricardo** [comment]
Thanks @demaya. That should be reviewed and approved by the German .org translation team.

**Comment by dougaitken** [comment]
I believe this is now resolved, but please reply if this is still a problem and detail steps I can take to try and replicate this.

**Comment by demaya** [comment]
This [translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe/stable/de/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12571385&filters%5Btranslation_id%5D=95327630) is still not approved. Any way to get some traction, @dougaitken  / @ricardo?

**Comment by dougaitken** [comment]
Hey @demaya Thanks for the ping! 

I don't have direct connection with anyone on the WordPress.org Plugins Translations team but I've asked some colleagues for advice on this one to see if we can move it along.

_Internal ref: p1669418563149339-slack-C02AED43D_

**Comment by dougaitken** [comment]
Following up here, this translation along with some others have been approved.
