### ISSUE TITLE
Potential duplicate webhook actions

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-stripe#2331]
**Describe the bug**
This issue already exists within [WooCommerce Payments](https://github.com/Automattic/woocommerce-payments/pull/3975), could the same thing also be happening in the Stripe extension itself?

I worked on a ticket this morning( 4902272-zen ) where they have said most of their recent Stripe orders have these duplicate order notes from Stripe regarding the charge. For example they see this twice or more on their orders.

> Stripe charge complete (Charge ID: ch_XXXXXX)

**To Reproduce**
I am not finding a specific way to replicate this as it doesn't happen on my local site in test mode, but it's happening just about every order on this customers site.

**Expected behavior**
No duplicate order notes. The customer thought customers were being charged twice, it doesn't seem that way since the charge IDs are the same in any duplicated or triplicated order notes.

**Screenshots**
![https://d.pr/i/zDbDvh](https://d.pr/i/zDbDvh+)
Image link: https://d.pr/i/zDbDvh

**Comment by dreamtooloud** [comment]
The user from zd-4902272 mentioned that they have the same plugins set up on a different server and they don't see the duplicate notes problem. I've asked for some additional information about the configuration and if they've reached out to their server at all (on the problem site we are currently troubleshooting) to see if it's a server related issue.

**Comment by dreamtooloud** [comment]
Another update from the same user. I had suggested (as a work around for their downloadable content issue) turning on the function to access download upon purchase, but they corrected what they said before about the payment statuses: 

"Seems the status is not in "Processing" after the Stripe payment is finished. It is in "Waiting for payment"." 

That means second status is triggering a push back to "pending payment" even though the payment has already been made. 

They also mentioned this about their other server's settings: For the other server, we are using the same version of WooCommerce Plugin and Stripe gateway plugin. Seems everything work normally on the server.

They have included the System status in their ticket. Let me know if you want me to add it here.

**Comment by shaunkuschel** [comment]
I took a look at 4902272-zen and noticed that there are quite a fatal errors occurring around when this duplicate note/status change is happening:

```
2022-04-09T03:57:37+00:00 CRITICAL Uncaught Error: Call to a member function get_sku() on null in /wordpress/plugins/woocommerce/6.3.1/templates/single-product/meta.php:28
Stack trace:
#0 /wordpress/plugins/woocommerce/6.3.1/includes/wc-core-functions.php(345): include()
#1 /wordpress/plugins/woocommerce/6.3.1/includes/wc-template-functions.php(1646): wc_get_template('single-product/...')
#2 /wordpress/core/5.9.3/wp-includes/class-wp-hook.php(307): woocommerce_template_single_meta('')
#3 /wordpress/core/5.9.3/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/5.9.3/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /srv/htdocs/wp-content/themes/flatsome/woocommerce/content-single-product-lightbox.php(57): do_action('woocommerce_sin...')
#6 /wordpress/plugins/woocommerce/6.3.1/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#7 /srv/htdocs/wp-content/themes/flatsome/inc/extensions/flatsome-wc-quick-view/flatsome-quick-view.php(41): wc_get_template('content-single-...')
#8 /wordpress/core/5.9.3/wp-includes/class-wp-hook.php(307): flatsome_quickview('')
#9 /wordpress/core/5.9.3/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#10 /wordpress/core/5.9.3/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#11 /wordpress/core/5.9.3/wp-admin/admin-ajax.php(202): do_action('wp_ajax_nopriv_...')
#12 {main}
  thrown 於 /wordpress/plugins/woocommerce/6.3.1/templates/single-product/meta.php on line 28
```

I suggested that they address that fatal error and see if that resolves the issue.

**Comment by thracefulton** [comment]
Another possible case in 4940814-zen.

**Comment by ryanr14** [comment]
I was working again on 4940814-zen and they don't have any fatal error logs available as in @shaunkuschel's case. Just as an FYI. They enabled Stripe logging once they noticed this happening, but I don't believe it's happened again since April 8th for their site.

**Comment by joaodante** [comment]
Another case here: 4965600-zen

The merchant commented it's not happening with ALL orders (but with most of them).

**Comment by thelogicwizards** [comment]
4940814-zen reports that the issue persists, but they recently shared that:

> Interesting to note that the doubling of logged ticket numbers on Order Details is no longer present on the affected orders, as far as we can tell, but the duplicate emails (obviously) and duplicate Stripe notices (but not charges) remain.

**Comment by aheckler** [comment]
12595841-hc which led to 5083355-zen was this. Merchant solved it by disabling this in the Stripe settings:

<img width="1253" alt="Screenshot taken on 2022-04-25 at 19 27 07 UTC@2x" src="https://user-images.githubusercontent.com/5512652/165160028-36a4e4c8-a7c6-4564-846a-d7b47d028e1d.png">

**Comment by thracefulton** [comment]
Another instance in 5167773-zen. I confirmed that this user did **not** have the Experimental "new checkout" active.

**Comment by lovo-h** [comment]
Just to clarify, this is not a case of duplicate webhook actions. Instead, it's the following:
1. The webhook action `payment_intent.succeeded` being called.
2. `add_action( 'wp', [ $this, 'maybe_process_upe_redirect' ] )` being called when UPE is enabled.

That's why the merchant that @aheckler brought up had success in solving the issue when they disabled UPE: they removed pathway 2 (i.e. `maybe_process_upe_redirect` call).

**1. The webhook action `payment_intent.succeeded` stacktrace**:
```php
abstract-wc-stripe-payment-gateway.php:539, WC_Stripe_Payment_Gateway->process_response()
class-wc-stripe-webhook-handler.php:854, WC_Stripe_Webhook_Handler->process_payment_intent_success()
class-wc-stripe-webhook-handler.php:990, WC_Stripe_Webhook_Handler->process_webhook()
class-wc-stripe-webhook-handler.php:70, WC_Stripe_Webhook_Handler->check_for_webhook()
```

**2. `add_action( 'wp', [ $this, 'maybe_process_upe_redirect' ] )` being called when UPE is enabled**:
```php
abstract-wc-stripe-payment-gateway.php:539, WC_Stripe_Payment_Gateway->process_response()
class-wc-stripe-upe-payment-gateway.php:923, WC_Stripe_UPE_Payment_Gateway->process_order_for_confirmed_intent()
class-wc-stripe-upe-payment-gateway.php:853, WC_Stripe_UPE_Payment_Gateway->process_upe_redirect_payment()
class-wc-stripe-upe-payment-gateway.php:822, WC_Stripe_UPE_Payment_Gateway->maybe_process_upe_redirect()
class-wc-stripe-intent-controller.php:680, WC_Stripe_Intent_Controller->maybe_process_upe_redirect()
```

These two pathways will need to be debugged and either the "Stripe charge complete" note needs to get removed from one or it may be a bit more involved and both of the pathways will need to be reevaluated.

**Comment by thisissandip** [comment]
5175398-zen

**Comment by stuartduff** [comment]
5202573-zen The particular customer within this support ticket is finding that due to the duplication stock quantities are being reduced twice.

**Comment by Gabriel-Denys** [comment]
I am actually experiencing the exact same issue. It happened to me exactly after I deleted a webhook and configured a new one.

I get duplicate order notes, duplicate emails, and stock being reduced twice.

The issue does not occour when a customer pays via Apple Pay. I have the new checkout experience enabled. 

I can share the logs if needed. 

Are there any solutions other than switching back to the old checkout?

**Comment by mouligreenlaw** [comment]
Hi there!
I'd like to update the merchant on 4940814-zen as to a possible release of this fix.
Is there anything I can tell them?

**Comment by solstudioim** [comment]
It was reported in 5334483-zen and 5339700-zen too.

**Comment by dreamtooloud** [comment]
Have another report of this here: 36018895-hc and follow up here: 5202573-zen 

Got creds to confirm relation to this bug--but I'm 99% sure it is connected base on the information the user provided.

**Comment by nicholasjeberlin** [comment]
5360179-zen

**Comment by LaurenceKay** [comment]
I am having this issue as well on 2 websites

Have just tried turning off new check out see if that resolves the issue.

**Comment by jos22** [comment]
5453836-zen. User is facing duplicate stock reduction on top of duplicate order notes just as @stuartduff mentioned.

**Comment by dreamtooloud** [comment]
Working on 5468298-zen where we have duplicate charge complete order notes plus duplicate points being awarded via WooCommerce Points and Rewards. Trying to confirm if it's related to this or not.

**Comment by mouligreenlaw** [comment]
Adding to @dreamtooloud comments relating to 5468298-zen
I looked at the orders received today, 11 Aug, and found that duplicate points were only awarded when Stripe was used and the customer had an account.
Out of 5 orders using Stripe, only one did not duplicate the Stripe note, and the two that had points applied show the  duplicate points.
All orders that used PayPal awarded points once as expected.
My thinking is that this is not a bug in Points & Rewards and it is caused by this bug in Stripe.
Note: EPU features are disabled on this site.

**Comment by LaurenceKay** [comment]
I have spent some time looking into this seems 99% sure its some thing to do with the Try the new checkout experience (early access)

i have 4 websites 2 which had this activated had the issue, since turning off haven't seemed to have the problem.

**Comment by dreamtooloud** [comment]
We mentioned to the user that we didn't think there duplicate notes/inventory reduction was related to this issue because they don't have UPE enabled but after looking through all the notes here and the other tickets I do want to add this to the list, because everything else about it is similar: 5539401-zen. 

Asking them to conduct a conflict test now to confirm the above.

**Comment by AbhinavSakalle** [comment]
5612750-zen
Duplicate order emails are also being sent.

**Comment by thisissandip** [comment]
Merchant from 5612750-zen deep dived into the issue and shared the below details:

> I found that not all orders were affected by the problem, so I analyzed the last 50 orders to try to see if the orders that have the problem have similarities between them, and this will allow you to analyze them too.
> I did not notice anything at the level of users (whether guest or registered), nor at the level of the amount of the order.
> So I looked for Stripe and the nature of the payments (issuing bank, type of bank card, etc.).
The result is here: https://docs.google.com/spreadsheets/d/14pmlKeMCBfHLh5LHUcRTq6IqQwdBDa36gKJ0zvV_OlM/edit?usp=sharing

> Unfortunately neither the issuing bank nor the type of card seems to affect the problem. However, I notice that the problem is less present for CB type cards.
> 3D secure, sometimes requested from the customer and sometimes exempted, does not seem to have any influence either.

> On the other hand, I noticed that the 3D secure information did not always appear in the logs. That is to say that for certain payments, I do not have the information if the exemption or the submission took place. And in this specific case, the problem is systematically present.
> The only exception is an iDEAL payment, but that's surely particular for this payment method. On the other hand, it seems important to me to note that the problem can exist for an alternative payment to the bank card (here iDEAL), contrary to what I had announced to you following the SOFORT payment which had worked.

> Here is an image: https://diamant-strass-dmc.com/3dsecure_test.png

> In my Drive table, the red terms in the image are listed in the "3D Secure" column.

> Finally, I would like to point out that I have activated all possible Webhooks in my Stripe account.

**Comment by joashrajin** [comment]
+1 at 5628841-zd-woothemes

In this case, the customer also noticed the order received email was being sent twice

**Comment by roryWolf** [comment]
This merchant is also experiencing duplicate emails being sent: 4940814-zen

**Comment by nekszt** [comment]
I am experiencing the same issue !
With this issue our users have a bad experience, pages refresh, duplicated emails, and also for us, data tracking, notifications ...

Is the issue well identified ?
Has anyone identified a quick fix ?

**Comment by nekszt** [comment]
Do you have feedback about translations, WPML ? A redirection caused by the translation and/or cookie setting about translation ?

**Comment by thisissandip** [comment]
While the team is looking into the issue, please use the workaround mentioned [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-1108954903)

- Disable the "New Checkout Experience" under **WooCommerce > Settings > Payments > Stripe > Settings > Advanced Settings:**

![lTKV1o.png](https://user-images.githubusercontent.com/69596988/199675133-3168b852-466e-4497-9ff6-7dbca5aaa43e.png)

**Comment by marissaexplores** [comment]
[5693996-zen](5693996-zd-woothemes)

**Comment by MartijnKaimea** [comment]
Thanks for the information thus far. I have the same issue. Be interested to see when this gets resolved. My contact with Woo Support resulted in this:

> Although this is a high-priority bug, we are unable to give an exact timeline for the fix at this time. While the developers are working on this, their official workaround is to disable the "New Checkout Experience" under WooCommerce > Settings > Payments > Stripe > Settings > Advanced Settings, as you mentioned in your findings.

For me, it doesn't really feel like a high-priority bug if it has been documented since April. I'll switch back to the 'old' checkout experience.

**Comment by wyter** [comment]
5936844-zen

**Comment by orhanfernandes** [comment]
5941928-zen

**Comment by darcie** [comment]
6293912-zen was facing duplicate order complete notifications. Disabling the new payment experience resolved the issue.

**Comment by ramshengale** [comment]
We're getting this exact same issue with new payment experience option enabled. This issue has been Open since last years. Can you please look into this?

**Comment by ryanr14** [comment]
8017760-zen

**Comment by sverleis** [comment]
8014478-zen

**Comment by TullariS** [comment]
Hi guys,

Having this issue as well. I've noticed in my case that if I use regular test cards you do not get a doubled-up order status change, but if you use a 3DSecure card, you do.

Hope this helps.

**Comment by bdawson-ssapopka** [comment]
We are also experiencing this error. We are using WooCommerce Stripe Gateway and WooCommerce Subscriptions, WooCommerce Memberships, and Teams for WooCommerce Memberships. We have the new checkout experience enabled and are running version 8.2.0 of WooCommerce Stripe Gateway.

The issue is more than just a charge note being applied twice to an order. We also see that the `WC_Order->status_transition()` function is being called twice by duplicate calls to `WC_Order->save()`. This is triggering the `woocommerce_order_status_pending` action hook to be fired twice, as seen here:

<img width="306" alt="Screen Shot 2024-04-30 at 11 04 25 AM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/102551815/c590d0af-ba76-4e5b-a433-87e00b4328e1">

The duplication stems from two processes that ultimately call a function in abstract `WC_Stripe_Payment_Gateway`. The following flows are the culprits according to my stack trace:

### WooCommerce Checkout AJAX Flow
```
WC_Order->status_transition()
WC_Order->save()
WC_Order->payment_complete()
WC_Stripe_Payment_Gateway->process_response()  //This is where the duplicate call is!
WC_Stripe_UPE_Payment_Gateway->process_payment_with_deferred_intent()
WC_Stripe_UPE_Payment_Gateway->process_payment()
WC_Checkout->process_order_payment()
WC_Checkout->process_checkout()
WC_AJAX::checkout()
``` 

### Stripe Gateway Webhook Flow
```
WC_Order->status_transition()
WC_Order->save()
WC_Order->payment_complete()
WC_Stripe_Payment_Gateway->process_response() //This is where the duplicate call is!
WC_Stripe_Webhook_Handler->process_payment_intent_success()
WC_Stripe_Webhook_Handler->process_webhook()
WC_Stripe_Webhook_Handler->check_for_webhook()
```

For now, I think we will have to disable the new checkout experience as we are trying to launch a website soon and this duplicate call to the `woocommerce_order_status_pending` hook causes significant problems for the WooCommerce Memberships for Teams team creation functionality. Hopefully this helps to fix the issue.

**Comment by ghost** [comment]
8109500-zen

**Comment by a-danae** [comment]
👋 hey! 

Are you still having this issue using [Stripe 8.3.1](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.3.1) or newer?

We introduced changes related to the process behind this behavior that could have solved it.

**Comment by menelaosc** [comment]
Hi

We still have this issue with 8.4.0. Is there an intermediate solution (besides returning to legacy mode) until the problem is resolved?

Thanks

**Comment by a-danae** [comment]
Thanks for confirming the issue still is present after 8.3.1, @menelaosc !

>  Is there an intermediate solution (besides returning to legacy mode) until the problem is resolved?

We don't have a temporary solution as of now because we have to dive into what's causing the problem. We'll update both GH issues as soon as we have news on this.

For future reference, this issue seems to be related to this other one https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463

**Comment by a-danae** [comment]
Hey folks, could you please confirm if the following scenario applies to any of you?

1. Go to your list of configured webhooks at https://dashboard.stripe.com/webhooks
2. Check out the table under "Hosted endpoints"
3. Do you have the same website URL in two rows or more? Like this
   <img width="700" alt="image" src="https://github.com/user-attachments/assets/d697b067-fa1d-429c-a9e3-f17ed95598c4">

I'm trying to understand what could be causing this behavior since things work as expected following the standard flows.

Update: To clarify, the main issue doesn't seem to be related to the double processing of webhooks, as [mentioned above](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-1111361275). Curious if that could be the case for some sites that could be easily solved.

**Comment by menelaosc** [comment]
Hi @a-danae 

Thanks for your help.

We only have one endpoint defined under "hosted endpoints" but still get duplicate notes and notifications.

Thanks

**Comment by carolframen** [comment]
8481374-zen

Another user commented on the thread about having the same issue and it being fixed when switching to the legacy checkout.

The Thread Starter mentioned stock is also being reduced twice.

**Comment by carolframen** [comment]
8494517-zen

**Comment by carolframen** [comment]
Hey @a-danae I asked a user to check what you mentioned here, and here's the screenshot from their end: https://snipboard.io/dxuL2c.jpg

**[here's the thread](https://wordpress.org/support/topic/woocommerce-sending-duplicate-emails-on-new-store-orders/#post-17901356)**.

**Comment by sophiegyo** [comment]
Just noting a potential report from 8497658-zen as the merchant is interested in the fix.

**Comment by OmarFPG** [comment]
8494517-zd

SSR for this one [here](https://wordpress.org/support/topic/woocommerce-sending-duplicate-emails-on-new-store-orders/#post-17908435).

**Comment by christofervas** [comment]
We have the same duplicate issue (version 8.5.2) for new orders only (it's not occur on renewal orders - we use WooCommerce Subscriptions).

**Comment by sophiegyo** [comment]
We may have a case in 8486169-zen too

**Comment by PaulSchiretz** [comment]
I also have this exact issue.

**Comment by WCSolution** [comment]
I also have this exact issue.

**Comment by AbhinavSakalle** [comment]
The issue was resolved after switching back to Legacy Checkout in 8497635-zen

**Comment by shameemreza** [comment]
Another report here: 8544193-zen
Thread link: https://wordpress.org/support/topic/webhook-called-twice/

**Comment by WCSolution** [comment]
> The issue was resolved after switching back to Legacy Checkout in 8497635-zen

This resolved my issue too

**Comment by shameemreza** [comment]
* Possibly another report here: 8547389-zen
* Suggested that switching back to Legacy Checkout.

**Comment by wyter** [comment]
Also reported on 8549523-zen

**Comment by wyter** [comment]
8461577-zen matches the behavior pattern of this bug as well.

**Comment by carolframen** [comment]
8554787-zen

**Comment by ghost** [comment]
Also reported here - 8550782-zen
Asked user to switch back to Legacy Checkout.

**Comment by ghost** [comment]
Another report here - 8494205-zen

**Comment by ghost** [comment]
8514891-zen

**Comment by livingperson** [comment]
> > The issue was resolved after switching back to Legacy Checkout in 8497635-zen
> 
> This resolved my issue too

This did NOT resolve my issue. It broke the store, and we immediately had zero sales, after dozens of sales that same day.  Once we lost a big number of sales, we had to switch back to turning off Legacy Checkout.

Who is working on this? Why is it not being solved?? It's been over two years!?!?

**Comment by wyter** [comment]
8572882-zen

**Comment by grig-23** [comment]
Some feedback from 8504106-zen.

> There is only one webhook URL in the Stripe dashboard. 

> I'm not a developer, but looking through the request code on an order with duplicate triggered events I notice the following:

> At the end of payment_intent.created (and similar for charge.succeeded)

`"livemode": true,
  "pending_webhooks": 1,
  "request": "req_EOrkvh6EpwdQ2I",
  "type": "payment_intent.created"`

> At the end of payment_intent.succeeded

`"livemode": true,
  "pending_webhooks": 2,
  "request": "req_EOrkvh6EpwdQ2I",
  "type": "payment_intent.succeeded"`

I hope this is helpful!

**Comment by ghost** [comment]
Another report here 8569907-zen

**Comment by AbhinavSakalle** [comment]
Reported in 8583108-zen

**Comment by a-danae** [comment]
Hey everyone! 👋 

Update over here. Would you please give the latest version a go? It's [8.6.1](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.6.1).

It was released twelve hours ago and it includes a fix for this issue.

Closing this GH issue as it should have been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3331.

Please let us know if you notice anything off after the update. Thanks again for your patience and the details you provided. We'll be around.

**Comment by TomasHurtz** [comment]
Hello I am still getting duplicate order emails being generated. How can I check if this is the same bug?

EDIT I just noticed I appear to be using the Stripe legacy checkout and I have no idea why. I will disable that and see what happens.

**Comment by bdawson-ssapopka** [comment]
Edit: I see that this was actively being monitored in an Epic (#3327) and multiple other issues, but that was closed, too.

This issue should not be closed as I am still experiencing this problem. I previously commented in this thread [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331#issuecomment-2085708821). I see there is a new issue that is addressing the same problem as well. The WooCommerce Stripe plugin is causing our customers to receive duplicate customer emails and causing WooCommerce to place duplicate order notes on order admin. We are running WooCommerce Stripe Gateway version 8.8.0, which we updated to after the changelog indicated this issue was fixed. Here are some recent screenshots of the symptoms:

Subscription Notes:
![Image](https://github.com/user-attachments/assets/0fb67a29-06ff-4fa1-a6de-6012b9f791f8)

Renewal Order Notes:
![Image](https://github.com/user-attachments/assets/9d0f440d-f139-4dba-9c30-6d6040d04cd8)

Email Log:
![Image](https://github.com/user-attachments/assets/26746610-4649-499a-a302-de207c8de92a)

**Comment by russdx** [comment]
I have the same issue as well with WooCommerce using latest stripe plugin 8.8.1

**Comment by clickstatement** [comment]
For anyone having this problem, we've had an issue with duplicate emails on and off for over a year now (Woocommerce / Woocommerce Subscriptions). What solved it, was disabling Object Cache on Cloudways. Hopefully this helps someone.

**Comment by ThyranWright** [comment]
Having the same issue double notes on orders creating duplicate emails. Woo Support suggested switching to legacy mode which I have but it has had no effect still experiencing the issue. Have disabled object cache as a test but that hasnt made a difference either. 

Edit: Updating to 8.8.2 fixed the issue

**Comment by mattallan** [comment]
Hi all, last week we released Stripe 8.8.2 which included a few key fixes to address the issues of duplicate order notes and emails on orders and subscription renewal orders:

- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3572
- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3575

For extra context, we found that stores with object caching enabled were having the webhook sent by Stripe processed concurrently with the original payment request. This resulted in us calling `$order->payment_complete()` twice as well as adding the "Stripe charge completed" order note multiple times.

Please update to the latest Stripe version and let me know if you're still noticing the issue.
There's multiple issues opened for this so I'm going to close this and continue any further investigation here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3501

**Comment by russdx** [comment]
Looks good since update.
