### ISSUE TITLE
iDeal payment completed but order status not updated to in progress

### ISSUE THREAD

**Issue by nothingmuch88** [woocommerce/woocommerce-gateway-stripe#3181]
Hi there, 

This is my first post on github so please bear with me. We have been in contact with both Stripe support and plugin support on the wordpress-forum. The wordpress support folks advised us to post here for further help. This is the link to the https://wordpress.org/support/topic/ideal-completed-but-order-cancelled/ 

What is happening: 
we have a woocommerce store and process orders with 3 payment methods: cash, cheque or iDeal. 
The problem is only with some orders paid with iDeal, not for other payment methods, not all orders paid with iDeal. 

What happens is that the customer completes the iDeal payment, Stripe is displaying the payment as completed. 
Their support helped us to check and there is nothing to be found on their side , they say. 

Then for the "problem" iDeal orders, after the order has been paid the order status is not updated at the woocommerce store. It's stuck in the "awaiting payment" status. There are no order details after the first "Stripe payment intention created" (the store is set to Dutch language so i'm sorry if there is a mismatch in translation but I think that is what is says: "Stripe betaal intentie aangemaakt (betaal intentie ID:"

So, most iDeal orders are correctly getting the order status update after stripe payment is completed but some are not. 
It happens on some days, not all days. It can happen at different times. It happens with different products and different customers. 

**Describe the bug**

**To Reproduce**
I understand this step for your process but we have tried many things but have not been able to reproduce this issue ourselves with the Stripe test mode, but nothing yet. The only thing we did not try is actually paying order after order with iDeal to see if the bug arrises, this is because it can be over 10 orders of iDeal going great and each payment will cost the stripe fee. So I hope you understand. 

As you can see in the wordpress forum thread there is no 

**Expected behavior**
If the payment is completed with iDeal at Stripe - the order status at WooCommerce should be updated to "in progress". 

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 6.5.2
 - WooCommerce Version 8.9.1
 - Stripe Plugin Version 8.3.1
 - Browser [e.g. chrome, safari] and Version - multiple - Chrome 125.0.6422.113
 - Any other plugins installed - please see forum thread

**Additional context**
Problem is quite recent, I can not find the date we updated but a little while and some updates from either woocommerce and / or stripe plugin this problem became a thing. 
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by OmarFPG** [comment]
8254027-zen.

Thanks for reporting!

**Comment by koendolron** [comment]
We are experiencing the same issue on our store:

- Only some iDeal payments are stuck on 'Pending payment'. The payments are getting through in Stripe.
- It happens infrequently, we can't see a pattern
- It does not happen on different payment methods

**Comment by roelbroersma** [comment]
> We are experiencing the same issue on our store:
> 
> * Only some iDeal payments are stuck on 'Pending payment'. The payments are getting through in Stripe.
> * It happens infrequently, we can't see a pattern
> * It does not happen on different payment methods

Did you just edited your message? I was mailed: 

> We updated the plugin to the latest version, but are still experiencing this issue.
> Aside from that we are also seeing orders that are being paid by iDeal that are stuck on 'Pending payment', whilst the payment did come through in Stripe. It happens only for orders paid by iDeal, and it happens infrequently and just for some orders. We can't see a pattern on our side. Maybe this is connected, maybe it's not...


Now, my question is:  I also experience that issue with 'double emails and double notes' in Stripe Plugin v8.2.0 version.
However, you say you are now also experiencing the 'pending payment' issue for IDeal.  Did you also noticed this in the previous Stripe Plugin v8.2.0 version?  Or only in the latest 8.3.1 version?

**Comment by koendolron** [comment]
Hi @roelbroersma,
No i did not edit my message, I posted in two different issues. The other message you received was from this issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463

I have been experiencing the double emails & double order notes since (at least) 8.2. Maybe even before.
The Pending Payment issue is most likely caused by 8.3.1. But I am not sure at this moment, and it is hard to check since we have a large amount of orders each day. Tomorrow I will reverse the plugin back to 8.2 to see if this resolves the Pending Payment issue.

**Comment by nothingmuch88** [comment]
I just checked my post at the wordpress forum and can see there we first reported it with Woocommerce Stripe Gateway 7.4.1 on March 28th. 

Maybe there is some connection with the release of iDeal 2.0? I can not find a date that was first used but from memory the news articles about that are around the same time?

**Comment by james-allan** [comment]
Hey @nothingmuch88 and others on this issue.

I believe we have fixed this issue in Stripe 8.5.0 which released in July - specifically via this change: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3217. 

As you have mentioned, this issue is intermittent (it's not consistant), those issues are harder to understand and find solutions for but I'll include an explainer for what I think was happening and how we've fixed it. 

---

Payment methods like iDEAL redirect the customer off site to their bank to complete the payment. iDEAL supports all major Dutch banks (~11) and so I suspect the bank the customer used may have been a cause of the randomness of this issue. 

With iDEAL we expected the flow to be this:

<p align="center">
<strong>Your checkout → their bank → back to your store → order processed</strong>
</p>

The problem occurs if the customer isn't redirected back to your store. This could happen if the bank didn't redirect the customer back or if the customer completed the payment on a different device (eg mobile phone). The Stripe plugin would be expecting them to return via a very specific URL we passed to Stripe and if they didn't, the order could be left in a pending-payment status. 

In 8.5.0 we fixed this by ensuring that if the customer doesn't return via that URL, we still process the order via the Webhook - the status transition could just be delayed slightly by ~2 minutes.

So I do think we have fixed this issue, but given it's intermittent, I cannot be 100% sure. Can you confirm you have webhooks set up?

**Comment by wjrosa** [comment]
I did some additional testing for this issue, and everything seems to be working fine now, as James said above. I will be closing this issue. If the issue is still happening for you, please reopen it to let us know, @nothingmuch88 .

**Comment by nothingmuch88** [comment]
Hi all, 

Our issue started to happen again. Because of the intermittent i'm not 100% sure what happened in between but the last couple of weeks we have been getting 4 or 5 a week on 1 specific site. All other iDeal orders are going through just fine. 

Still the same issue: stripe is completed but in woocommerce the order is stuck on the status of "awaiting payment" and there is no 'order note'. I have added the logs below. 

Wordpress = 6.8.2
Woocommerce = 10.2.0
Stripe plugin = 9.9.1


so here's what I think is the log for the specific order:



`2025-09-21T15:39:35+00:00 Foutopsporing Stripe API request: GET payment_methods/pm_1S9pMQP94vRz6kkbYrGgWOuA  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20"
}

2025-09-21T15:39:35+00:00 Foutopsporing Stripe API response: GET payment_methods/pm_1S9pMQP94vRz6kkbYrGgWOuA  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "response": {
        "id": "pm_1S9pMQP94vRz6kkbYrGgWOuA",
        "object": "payment_method",
        "allow_redisplay": "unspecified",
        "billing_details": {
            "address": {
                "city": “[redacted]”,
                "country": "NL",
                "line1": "[redacted]",
                "line2": "",
                "postal_code": "[redacted]",
                "state": ""
            },
            "email": "[redacted]",
            "name": "[redacted]",
            "phone": "[redacted]",
            "tax_id": null
        },
        "created": 1758469174,
        "customer": null,
        "ideal": {
            "bank": null,
            "bic": null
        },
        "livemode": true,
        "metadata": {},
        "type": "ideal"
    }
}

2025-09-21T15:39:35+00:00 Foutopsporing Stripe API request: GET payment_methods/pm_1S9pMQP94vRz6kkbYrGgWOuA  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20"
}

2025-09-21T15:39:35+00:00 Foutopsporing Stripe API response: GET payment_methods/pm_1S9pMQP94vRz6kkbYrGgWOuA  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "response": {
        "id": "pm_1S9pMQP94vRz6kkbYrGgWOuA",
        "object": "payment_method",
        "allow_redisplay": "unspecified",
        "billing_details": {
            "address": {
                "city": "[redacted]",
                "country": "NL",
                "line1": "[redacted]",
                "line2": "",
                "postal_code": "[redacted]",
                "state": ""
            },
            "email": "[redacted]",
            "name": "[redacted]",
            "phone": "[redacted]",
            "tax_id": null
        },
        "created": 1758469174,
        "customer": null,
        "ideal": {
            "bank": null,
            "bic": null
        },
        "livemode": true,
        "metadata": {},
        "type": "ideal"
    }
}

2025-09-21T15:39:35+00:00 Foutopsporing Stripe API request: POST payment_intents  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "request": {
        "shipping": {
            "name": "[redacted]",
            "address": {
                "line1": "[redacted]",
                "line2": "",
                "city": "[redacted]",
                "country": "NL",
                "postal_code": "[redacted]",
                "state": ""
            }
        },
        "payment_method": "pm_1S9pMQP94vRz6kkbYrGgWOuA",
        "capture_method": "automatic",
        "mandate_data": {
            "customer_acceptance": {
                "type": "online",
                "online": {
                    "ip_address": "84.104.127.210",
                    "user_agent": "WooCommerce Stripe Gateway9.9.1; https://[redacted]"
                }
            }
        },
        "return_url": "https://[redacted]/afrekenen/order-received/78259/?key=wc_order_Roc9wF0oktd4l&order_id=78259&wc_payment_method=stripe&_wpnonce=53557f0d46&save_payment_method=no&pay_for_order=no",
        "amount": 5850,
        "confirm": "true",
        "currency": "eur",
        "customer": "[redacted]",
        "description": "[redacted] - Order 78259",
        "metadata": {
            "customer_name": "[redacted]",
            "customer_email": "[redacted]",
            "site_url": "https://[redacted]",
            "order_id": "78259",
            "order_key": "wc_order_Roc9wF0oktd4l",
            "payment_type": "single",
            "signature": "78259:fe435b8ad0fb9b6c650b4e36f11c10f7",
            "tax_amount": 0,
            "is_legacy_checkout_enabled": "no",
            "is_oc_enabled": "no",
            "pmc_enabled": "yes"
        },
        "payment_method_types": [
            "ideal"
        ]
    }
}

2025-09-21T15:39:35+00:00 Foutopsporing Stripe API response: POST payment_intents  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "response": {
        "error": {
            "code": "resource_missing",
            "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
            "message": "No such customer: 'cus_SxmMg4BGh7eZoe'",
            "param": "customer",
            "request_log_url": "https://dashboard.stripe.com/acct_1QBzIvP94vRz6kkb/logs/req_UIBo5kZRUhvZGj?t=1758469175",
            "type": "invalid_request_error"
        }
    }
}

2025-09-21T15:39:35+00:00 Foutopsporing Stripe API request: POST customers  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "request": {
        "email": "[redacted]",
        "description": "Naam: [redacted], gebruikersnaam: [redacted]",
        "name": "[redacted]",
        "metadata": [],
        "preferred_locales": [
            "nl-NL"
        ],
        "address": {
            "line1": "[redacted]",
            "line2": "",
            "postal_code": "[redacted]",
            "city": "[redacted]",
            "state": "",
            "country": "NL"
        },
        "order": {
            "customer_id": null,
            "refunds": []
        }
    }
}

2025-09-21T15:39:36+00:00 Foutopsporing Stripe API response: POST customers  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "response": {
        "id": "cus_T61PCymnL3bNUZ",
        "object": "customer",
        "address": {
            "city": "[redacted]",
            "country": "NL",
            "line1": "[redacted]",
            "line2": "",
            "postal_code": "[redacted]",
            "state": ""
        },
        "balance": 0,
        "created": 1758469176,
        "currency": null,
        "default_source": null,
        "delinquent": false,
        "description": "Naam: [redacted], gebruikersnaam: [redacted]",
        "discount": null,
        "email": "[redacted]",
        "invoice_prefix": "OQ0PGTBC",
        "invoice_settings": {
            "custom_fields": null,
            "default_payment_method": null,
            "footer": null,
            "rendering_options": null
        },
        "livemode": true,
        "metadata": {},
        "name": "[redacted]",
        "phone": null,
        "preferred_locales": [
            "nl-NL"
        ],
        "shipping": null,
        "tax_exempt": "none",
        "test_clock": null
    }
}

2025-09-21T15:39:37+00:00 Foutopsporing Stripe API request: POST payment_intents  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "request": {
        "shipping": {
            "name": "[redacted]",
            "address": {
                "line1": "[redacted]",
                "line2": "",
                "city": "[redacted]",
                "country": "NL",
                "postal_code": "[redacted]",
                "state": ""
            }
        },
        "payment_method": "pm_1S9pMQP94vRz6kkbYrGgWOuA",
        "capture_method": "automatic",
        "mandate_data": {
            "customer_acceptance": {
                "type": "online",
                "online": {
                    "ip_address": "84.104.127.210",
                    "user_agent": "WooCommerce Stripe Gateway9.9.1; https://[redacted]"
                }
            }
        },
        "return_url": "https://[redacted]/afrekenen/order-received/78259/?key=wc_order_Roc9wF0oktd4l&order_id=78259&wc_payment_method=stripe&_wpnonce=53557f0d46&save_payment_method=no&pay_for_order=no",
        "amount": 5850,
        "confirm": "true",
        "currency": "eur",
        "customer": "cus_T61PCymnL3bNUZ",
        "description": "[redacted] - Order 78259",
        "metadata": {
            "customer_name": "[redacted]r",
            "customer_email": "[redacted]",
            "site_url": "https://[redacted]",
            "order_id": "78259",
            "order_key": "wc_order_Roc9wF0oktd4l",
            "payment_type": "single",
            "signature": "78259:fe435b8ad0fb9b6c650b4e36f11c10f7",
            "tax_amount": 0,
            "is_legacy_checkout_enabled": "no",
            "is_oc_enabled": "no",
            "pmc_enabled": "yes"
        },
        "payment_method_types": [
            "ideal"
        ]
    }
}

2025-09-21T15:39:38+00:00 Foutopsporing Stripe API response: POST payment_intents  
Aanvullende context
{
    "stripe_version": "9.9.1",
    "stripe_api_version": "2024-06-20",
    "response": {
        "id": "pi_3S9pMTP94vRz6kkb0TgEL3FK",
        "object": "payment_intent",
        "amount": 5850,
        "amount_capturable": 0,
        "amount_details": {
            "tip": {}
        },
        "amount_received": 0,
        "application": "ca_BC3QvYOCCxiOW3Klo6zL8KlBgSHzwTKn",
        "application_fee_amount": null,
        "automatic_payment_methods": null,
        "canceled_at": null,
        "cancellation_reason": null,
        "capture_method": "automatic",
        "client_secret": "pi_3S9pMTP94vRz6kkb0TgEL3FK_secret_2F54Jv9LPmYemMhHRmWAyd2V7",
        "confirmation_method": "automatic",
        "created": 1758469177,
        "currency": "eur",
        "customer": "cus_T61PCymnL3bNUZ",
        "description": "[redacted] - Order 78259",
        "excluded_payment_method_types": null,
        "invoice": null,
        "last_payment_error": null,
        "latest_charge": null,
        "level3": null,
        "livemode": true,
        "metadata": {
            "customer_email": "[redacted]”,
            "customer_name": "[redacted]",
            "is_legacy_checkout_enabled": "no",
            "is_oc_enabled": "no",
            "order_id": "78259",
            "order_key": "wc_order_Roc9wF0oktd4l",
            "payment_type": "single",
            "pmc_enabled": "yes",
            "signature": "78259:fe435b8ad0fb9b6c650b4e36f11c10f7",
            "site_url": "https://[redacted]",
            "tax_amount": "0"
        },
        "next_action": {
            "redirect_to_url": {
                "return_url": "https://[redacted]/afrekenen/order-received/78259/?key=wc_order_Roc9wF0oktd4l&order_id=78259&wc_payment_method=stripe&_wpnonce=53557f0d46&save_payment_method=no&pay_for_order=no",
                "url": "https://pm-redirects.stripe.com/authorize/acct_1QBzIvP94vRz6kkb/pa_nonce_T61PS5wqk7O9Hnzeg4cHKArrGdnYL2I"
            },
            "type": "redirect_to_url"
        },
        "on_behalf_of": null,
        "payment_method": "pm_1S9pMQP94vRz6kkbYrGgWOuA",
        "payment_method_configuration_details": null,
        "payment_method_options": {
            "ideal": {}
        },
        "payment_method_types": [
            "ideal"
        ],
        "processing": null,
        "receipt_email": null,
        "review": null,
        "setup_future_usage": null,
        "shipping": {
            "address": {
                "city": "[redacted]",
                "country": "NL",
                "line1": "[redacted]",
                "line2": "",
                "postal_code": "[redacted]",
                "state": ""
            },
            "carrier": null,
            "name": "[redacted]",
            "phone": null,
            "tracking_number": null
        },
        "source": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "requires_action",
        "transfer_data": null,
        "transfer_group": null
    }
}

2025-09-21T15:40:38+00:00 Foutopsporing 

====Stripe Version: 9.9.1====

====Stripe Plugin API Version: 2024-06-20====

`

**Comment by nothingmuch88** [comment]
@wjrosa the "reopen issue" is disabled, maybe because the issue is to old. I'm not sure, not an expert on github. Could you please help us to reopen this issue?
