### ISSUE TITLE
Focus Loss in WooCommerce Checkout with Stripe Payment Gateway

### ISSUE THREAD

**Issue by avs-22** [woocommerce/woocommerce-gateway-stripe#4142]
**Description of the Issue**

When using Stripe payment gateway on WooCommerce checkout (wc-block-components-form wc-block-checkout__form), customers experience a severe usability issue where input fields lose focus after each keystroke. This makes completing the checkout form almost impossible as users must constantly re-click the field to continue typing. The issue affects all standard checkout fields (email, name, address, etc.) but does not affect Stripe's own payment fields. 

The error is resolved if you refresh the page after the complete checkout page is loaded and also if you disable the stripe plugin.

**Reproduction Steps**

1. Use incognito/private mode in Chrome or Safari
2. After each testing session, clear browser cache
3. Also clear "customer sessions" in WooCommerce > Status > Tools

If you don't clear both the cache and customer sessions, the error will not appear as the page refresh fix remains in effect. The error will only reappear based on the WooCommerce site setting for resetting customer sessions and browser caching of the user.

**Root Cause Analysis**

Through debugging and console monitoring, we identified the exact sequence causing the issue:

When a user types in a regular checkout field (e.g., shipping-first_name), the field loses focus
Focus briefly shifts to Stripe's hidden input element (wc-stripe-hidden-input)
Focus then moves to the body element
This sequence repeats after each keystroke

Console output when monitoring blur events shows:

Blur event on:  input type="text" id="shipping-first_name"...
Focus going to:  body class=...
Event triggered by: <input type="text" id="wc-stripe-hidden-input"...>
The issue appears to originate from Stripe's UPE (Unified Payment Element) implementation in the file upe_blocks.js, which is managing state by temporarily shifting focus to its hidden input but failing to return focus properly.

**Temporary Workaround**

The issue mysteriously resolves itself when the checkout page is refreshed. This indicates a potential initialization issue or state management problem in the Stripe UPE code.

For now, we have implemented a minor fix where we are running a small JavaScript script on the checkout page to refresh only once after the page has loaded completely. A key finding during implementation was that we had to wait a minimum of 300ms after complete load before triggering the refresh. If the refresh occurs too soon (less than 300ms after complete page load), the error persists.

Environment:
1. WordPress version: 6.7.2
2. WooCommerce version: 9.7.1
3. Woocommerce Stripe plugin version: 9.3.1
4. Checkout implementation: WooCommerce Blocks (form class: "wc-block-components-form wc-block-checkout__form")
5. Affects all browsers and devices (desktop and mobile)
6. Issue started after updating the Stripe plugin from 9.1 to latest
7. If we disable stripe plugin issue is not present.

Additional Information

1. The issue does not appear in the browser console as a JavaScript error
2. Creating a JavaScript fix to force focus back to the original field works but causes typing lag
3. Multiple users have reported abandoning checkout due to this issue
4. The problem affects conversion rates as it makes completing the form extremely frustrating
5. The issue reproduces consistently across all tested environments

We would appreciate a prompt investigation into this issue as it's significantly impacting our checkout conversion rate.

**Comment by ehclau** [comment]
I've also been experiencing this reliably when developing locally with wp-env. Here's a video recording in case anyone needs one. Definitely a massive cart abandonment issue.

https://github.com/user-attachments/assets/a60f2a3d-a3bb-4d19-9c98-8ec45e34343f

**Comment by ehclau** [comment]
Below is a full video of the repro on a fresh boot using a simple wp-env environment with the wp-env.json settings below and the Twenty-twenty-five block theme. Not sure if this is of importance, but note that I focused on an input before the stripe elements appeared. Once they appear, focus was automatically lost before I had typed anything. Subsequent inputs will lose focus upon typing a single character as described by this ticket.

```
{
	"config": {
		"WP_DEBUG": true,
		"SCRIPT_DEBUG": true,
		"WP_DEBUG_LOG": "/tmp/wp-errors.log",
		"FS_METHOD": "direct",
		"WP_ENVIRONMENT_TYPE": "local"
	},
	"core": null,
	"phpVersion": "8.3",
	"plugins": [
		"https://downloads.wordpress.org/plugin/woocommerce.9.7.0.zip",
		"https://downloads.wordpress.org/plugin/woocommerce-gateway-stripe.9.2.0.zip"
	]
}

```

https://github.com/user-attachments/assets/68e6ec5c-9494-40e1-b023-b193ba41fe26

**Comment by avs-22** [comment]
@ehclau thanks for the repro video for the issue. Im surprised this hasn’t been flagged earlier. My only assumption is that not a lot of people have updated to the latest version of the plugin. We were only able to find this error because our cart abandonment for new customers sky rocketed, and we had to investigate. I hope this is addressed soon.

**Comment by Swapot** [comment]
I requested help for this issue in the Woocommerce Stripe support forum a few weeks ago, but I was not able to keep reproducing the issue:

https://wordpress.org/support/topic/stripe-and-paypal-payments-conflict/

**Comment by avs-22** [comment]
@Swapot Im not sure about any PayPal conflict in particular, but we tested this on an our staging server with only the stripe plugin active, and the issue is present. If you do the following before each retest the issue is always reproduced. 

1. Use incognito/private mode in your browser
2. Clear woocommmerce customer sessions
3. Clear browser cache. 

We haven’t had issues with old user accounts because in most cases their information is already saved, so they don’t interact with any of the input fields or maybe there’s some caching that fixes it - for some reason when you refresh the checkout page the issue gets resolved. 

For now, as I stated in my initial post, we have added some js to refresh the checkout page after loading is complete, and added some messaging alerting the user that the page is being loaded.

**Comment by ClickUpp** [comment]
I have the exact same issue reported by a customer. Adding a video here.

Please increase the priority of this issue.

https://github.com/user-attachments/assets/7f5cc202-b975-4823-ad25-c0304783f06f

**Comment by ghost** [comment]
I have the exact same issue reported by a customer. Adding a video here.

Please increase the priority of this issue.

https://github.com/user-attachments/assets/cad5cad7-a627-4d03-b823-04e7b4e3a078

**Comment by malithsen** [comment]
Thanks for the report and reproduction steps everyone. Looks like we had this issue dormant for a while, but it started being more visible after some recent changes made in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3795. Fixed with https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4178

**Comment by Jhonmacc** [comment]
I'm also having the same problem on my clients' websites. My wordpress and plugins are all up to date. 
WordPress: Version 6.7.2
WooCommerce Stripe Gateway: Version 9.4.1 
I've tested it on several different browsers and devices like cell phones and iPads and the problem persists.
[Watch the video](https://i.imgur.com/EasSNUj.mp4)

**Comment by daledupreez** [comment]
Thanks for letting us know, @Jhonmacc! Unfortunately this fix is not in 9.4.1 as we had some stability problems in the original 9.4.0 release. It should be included in our upcoming 9.5.0 release, which we have scheduled for the week after next.
